version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
      - db_volume:/app/database/  
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate &&
             uvicorn LabForm.asgi:application --host 0.0.0.0 --port 8000"

volumes:
  db_volume: